### PR TITLE
Fix fmpy use

### PR DESCRIPTION
**Pull request by fcollonval**
This fix the ability to use the FMU with [FMPy](https://github.com/CATIA-Systems/FMPy) by handling correctly the GIL.

Not this does not use subinterpreter due to lack of knowledge on GIL and thread stuff in C-Python. See #52

### CODE REVIEW

**Comment by fcollonval** [comment]
@markaren could you please check that this PR is not breaking the use of the FMU with FMI4J?

**Comment by markaren** [comment]
Seems ok with FMI4j :)

**Comment by markaren** [comment]
Wait a second. I got a freeze. Lemme restart and see if it happens again.

**Comment by markaren** [comment]
Bad news. It's seems this PR breaks usage in threaded environments. I'm using a CLI that uses FMI4j to run the FMU. It work with plain FMI4j, but hangs using the CLI that runs the FMUs with threads.

**Comment by markaren** [comment]
I'm pretty sure this is PythonFMU issue as FMUs are required to handle access from multiple threads, which I think is the issue here.

**Comment by fcollonval** [comment]
That was my fear... playing with threads and the Python Global Interpreter Lock is a sensitive zone in Python 😩

**Comment by markaren** [comment]
```
            PyEval_InitThreads();
            PyThreadState* mainPyThread = PyEval_SaveThread();
```

Seems to be all thats needed...

**Comment by markaren** [comment]
To good to be true. FMPy, PyFMI and multiThread FMI4j works. But not plain FMI4j

**Comment by markaren** [comment]
Wait, it crashes on `serializedFMUstateSize` which I only call from plain FMI4j.

**Comment by markaren** [comment]
This works for me in all tested cases

**Comment by fcollonval** [comment]
You rock @markaren 

I was reading on the subject and found just that too; 

https://stackoverflow.com/questions/10625584/embedding-python-in-multithreaded-c-application

It is recommended to carry the restore the state (see for example In https://www.slideshare.net/YiLungTsai/embed-python slide 26).

If you could check the latest version, it would be great. And thanks again for digging on this one.

**Comment by markaren** [comment]
It's 3-4% slower than master, but we just have to roll with it.

**Comment by fcollonval** [comment]
Thanks for merging.

The overhead is important for what seems a small change. But as you said, we have to live with it.

I'll do a release by tomorrow noon.

**Comment by markaren** [comment]
Come to think about it. If the GIL thingy is only required if `_was_Initialized=true` (isit?), then we could avoid the overhead by conditionally call the GIL code. Right?

**Pull request merged**
