### PR TITLE
Getter setter improvements

### LINKED ISSUE #23: Rename internal getters and setters
Rename internal getters and setter which uses \_\_XXX__ method names to __XXX

### PR DESCRIPTION
**Pull request by fcollonval**
Fix #23 

Additional actions:
- Use more pythonic behavior (getter returns the variable list)
- Define simpler `get_value` and `set_value` method to simplify interfacing with third-party Python code - instead of having to override all `get_` and `set_` methods.

### CODE REVIEW

**Comment by fcollonval** [comment]
@markaren 

I have a problem when testing this one.
I extended the default case to add variables of all possible types as input and output. The integration test is consequently failing in `pyfmi` due to that call (in that library):

https://github.com/modelon-community/PyFMI/blob/df8228d4d97cfde3cd3fc321a4f3da31b417d4be/src/pyfmi/fmi_util.pyx#L312

I don't see anything in the standard forbidding to call `get_type` on variable having a different type. So my question is: is there a bug in `pyfmi` or should we support that case?

**Comment by markaren** [comment]
I don't understand your question. It looks like you are trying to call get_real (in PythonFMU) with a variable that is not Real.. ?

**Comment by fcollonval** [comment]
In pyfmi, they use that call to gather all the results:

```python
data = np.append(np.append(np.append(model.time, model.get_real(param_real)),model.get_real(param_int)),model.get_real(param_bool))
```

This results in a type error as `pythonfmu` forbids to request `get_real` on non-*Real* variables.

Is that call a bug in pyfmi or should we support that case - meaning casting type if needed?

**Comment by markaren** [comment]
IMO that's a bug in `pyfmi` and we should not support it. Since valuereferences in the FMI standard are unique to the base class they break the standard by doing so. E.g. A valueReference=1 could refer to both a Real and Integer.

**Comment by markaren** [comment]
LGTM!

**Comment by fcollonval** [comment]
@markaren could you please have a second look?

This includes also a fix on the stringified boolean value not being valid xs:boolean.

**Comment by markaren** [comment]
So I ran a performance comparison with master running PythonSlave.fmu with dt=0.001 and t=1000.
Master branch has a real-time-factor of 16.5, while this branch sees 13.3. I.e a performance decrease of almost 20%...

While the code looks good, I don't think we can allow such a huge hit on performance. It's not the most scientific benchmark, but..

**Comment by markaren** [comment]
Ahh, wait. This branch adds additional variables.. Let me re-test with those added on master!

**Comment by markaren** [comment]
We're all good performance wise! This branch is as fast if not faster than master with the same variables added!

**Pull request merged**
