### PR TITLE
Misc fixes.

### PR DESCRIPTION
**Pull request by markaren**
Fixes:
* strings goes out of scope (!!) <-- crashed on reset on my PC today. Not yesterday.
* remove loggingOn which is not actually loggingOn

Adds:
* pass resources to slave

Changes:
* Store pClass_ rather than pModule_

### CODE REVIEW

**Comment by fcollonval** [comment]
@markaren Thanks for those improvements.

Could you give some details on the use case for passing "resources" to the Python code?

Regarding `loggingOn`, what about passing it ? The "error" is located there:

https://github.com/NTNU-IHB/PythonFMU/blob/0c7328c6cb8c8ed038c38c408002deb777e3f5e3/pythonfmu/pythonfmu-export/cpp/fmi_functions.cpp#L78-L87

**Comment by markaren** [comment]
> Could you give some details on the use case for passing "resources" to the Python code?

It's needed if the FMU relies on additional files like .csv files. These arre supposed to be sshipped in within the resources folder of an FMU. However, come to think about. Since the script file itself is such a resource, any files it references with a relative path will still work as long as the user passes the entire project structure to the builder. 

> Regarding loggingOn, what about passing it ?

 I think we should wait until we actual use for it.

**Comment by markaren** [comment]
So basically, passing `resources` is unnecessary as we can get the same value calling `Path(__file__).parent`

**Comment by markaren** [comment]
I kept the `resources` as  the natural place to call `Path(__file__).parent` would be in `Fmi2Slave.py`, but then it would be wrong. FMI users would expect the API to provide the location of the resources by default, so I think this is the best solution.

**Pull request merged**
