### PR TITLE
Feature/rollback

### LINKED ISSUE #22: Support rollback
Since we have full control over all variable reads and writes it is very much possible to support rollback without the user even knowing it. Although I'm not in a hurry implementing it.

### PR DESCRIPTION
**Pull request by markaren**
This PR enables rollback of the FMU state. Tested with FMI4j.

Cavecat: It will only work if every single value changing variable used in the script is registered as an FMI variable. Therefore the xml should not say `canGetAndSetFMUstate=true` by default. As a result this flag should be explicitly enabled by the user using the builder cli. 
@fcollonval What do you think? 

Closes #22

### CODE REVIEW

**Comment by markaren** [comment]
Known issues with the PR: 
  * freeFMUstate has no effect
  * getFMUstate does not re-use memory

**Comment by fcollonval** [comment]
Awesome @markaren 

Regarding the issues you mention, does that mean the state should be stored in some variable in `SlaveInstance` class independently of the python wrapper?

**Comment by markaren** [comment]
I tried to re-use the memory by allocating the dict in C++ and pass it to `_get_fmu_state(self, state: Dict[int, Any])`, but I got weird errors when trying to send it to the Python function. We never call `Py_DECREF` at this point, so the object should live until the pointer is `Py_DECREF` in `free_fmu_state` on the native side.

**Comment by markaren** [comment]
I think this is good enough for a merge. Free works now, but memory is not re-used. But that's not a blocker.

User must enable support for this in importing tool by passing the `--handle-state` flag.

**Comment by markaren** [comment]
However, I have some doubt about it. Is this useful in practice?

**Pull request merged**
