### PR TITLE
Support nested variables

### LINKED ISSUE #79: Support nested variables
E.g `helper.myReal`

### PR DESCRIPTION
**Pull request by markaren**
Closes #79

### CODE REVIEW

**Comment by markaren** [comment]
I would image this is much slower then storing the owning reference? Can do I test tomorrow. I'd favour the initial version if that's the case. Most real life models would have nested variables I'd imagine.

**Comment by fcollonval** [comment]
Hey Lars, I thought more about this over night.

Let me first describe our use case, we have a simulation software in Python. The physical model is contained in a `CarPhysicalModel` instance named for e.g. `my_car`. When exposing it as FMU through PythonFMU (which is an optional feature), the Python slave looks like:

```python
from custom_lib import CarPhysicalModel

class CarPhysicalModelFMU(Fmi2Slave):
    
    def __init__(self):
        self.__model = CarPhysicalModel(name='my_car')
        self.register_variable(Real("steering_wheel.angle", causality=Fmi2Causality.input))
        self.register_variable(Real("speed", causality=Fmi2Causality.local))
        
    def get_value(self, name):
        return self.__model.get(name) # This is my concern as it depends on the data model

    def set_value(self, name, value):
        return self.__model.set(name, value) # This is my concern as it depends on the data model
```

So the name of the variables are not directly matching any python object structure. And I think we should not force the data structure to keep it as generic as possible.

You are probably right about the performance hit for non-direct attribute (for direct attribute the `try-except` keep the code *fast*). So if storing the owning reference is needed, the method to obtain it should be easily overwritten by the user to adapt it to its Python code.

> Note: I made a mistake by force pushing my proposal, sorry about that. You can get back your version with the following commit: https://github.com/NTNU-IHB/PythonFMU/tree/89064cdb8d4b2bc8ca1192e83435bdc5d4aed8fa

**Comment by markaren** [comment]
In that example why not name `__model` `car` and pass `car.steering_wheel.angle` as the variable name ? Then you would not even need to ovveride get/set. Are there more use cases that break?

**Comment by markaren** [comment]
Storing the owning reference is 8% faster when running the updated `pythonslave.py` with two nested variables. Image if all variables are nested. I ran 14000 doSteps.

**Comment by markaren** [comment]
An alternative approach of supporting your use case @fcollonval is to support function variables.

```python

class Slave(Fmi2Slave):

  def __init__(**kwargs):
    super().__init(**kwargs)
    self.var = SomeClass()
    self.register_function(Real("var"))
  
  def get_var():
    return self.var.XXX

  def set_var(value):
    self.var.XXX = value
    


```

**Comment by markaren** [comment]
This last version should be compatible with your current use-case, but it runs a little bit slower than mater due to an addition `isinstance` check.

**Comment by markaren** [comment]
Actually, we don't need to overload for `str` and `ScalarVariable` in get/set. `_set_fmu_state` should just use `setattr` directly and your overridden functions should use `var.name`.

**Comment by markaren** [comment]
Ok, new approach. We are now using overridable lambdas.

Your code will now look like this:

```python
from custom_lib import CarPhysicalModel

class CarPhysicalModelFMU(Fmi2Slave):
    
    def __init__(self):
        self.__model = CarPhysicalModel(name='my_car')
        self.register_variable(Real("steering_wheel.angle", causality=Fmi2Causality.input, getter=lamda: self.__model.get("steering_wheel.angle"), setter=lambda v: self.__model.set("steering_wheel.angle", v)))
        self.register_variable(Real("speed", causality=Fmi2Causality.local, getter= lamda: self.__model.get("speed"), setter=lambda v: self.__model.set("speed", value))))

```

**Comment by markaren** [comment]
Nice. I will merge in some improvements you made in the other branch. Or do you want to do it?

**Comment by markaren** [comment]
Do you want the lambda to return the name of the variable. Not just the void/new value?

**Comment by fcollonval** [comment]
> Nice. I will merge in some improvements you made in the other branch. Or do you want to do it?

Go for it.

> Do you want the lambda to return the name of the variable. Not just the void/new value?

I'm fine with the current implementation. What use case do you have in mind for returning the variable name?

**Comment by markaren** [comment]
In your example code, you'd need to copy the variable name 3 times.

**Comment by fcollonval** [comment]
Don't worry about that. I'm generating the code through template. Thanks for asking.

**Pull request merged**
