### PR TITLE
WIP: Adding callbacks to transfer log message

### LINKED ISSUE #35: Enhance logging
FMI defines a logger mechanism. Python itself has a standard logging library. A good enhancement would be to redirect the Python logger to the FMI one.

In addition, the support for the debug log flag at FMU instantiation should be added.

### PR DESCRIPTION
**Pull request by fcollonval**
Fix #35 

@markaren I need your help on this one.

For passing the log message from Python to the FMU facade, it seems the best is to load a customized python module within the embedded python instance.

I defined such module in `pythonfmu/pythonfmu-export/headers/pythonfmu/callbacks.cpp`. The python module is called `fmi2facade` and has 2 functions: `test` and `log`. The first one receive a string from python and print it to stdout and in the second I'm trying to invoke the FMU logger.

The `test` function works as expected but the `log` function ends up with a `Segmentation fault`; you can try the unit test `pythonfmu/tests/test_python_extension.py`.

This is beyond my knowledge of C/C++. If by any chance you get some times to look into this, it will be great.

Note: I also have a problem on the best way to store the pointer to the logger function; using a static attribute does not look good.

### CODE REVIEW

**Comment by markaren** [comment]
I think there is an easier way to do this. I believe it should be possible to pass the pointer to `Logger` in the `**kwargs`. Then define a C function that takes the pointer and a message loaded using ctypes.

**Comment by fcollonval** [comment]
Thanks for having a look and for the nice idea. I'll look into this (but
probably not before next week).

**Comment by markaren** [comment]
I had a go at this one. It's quite easy to do.

Basically you define a C function.

```cpp
extern "C" {

void log_info(void* logPtr, const char* msg)
{
    cppfmu::Logger* logger = ((cppfmu::Logger*) logPtr);
    logger->Log(fmi2OK, "", msg);
}

}

```

You can then call this from Python like so:

```python
    def log_info(self, msg):
        lib = cdll[f"{self.modelName}.dll"]
        lib.log_info(c_void_p(self.logger), c_char_p(msg.encode("utf-8")))
```

**Comment by fcollonval** [comment]
Superseeded by #86

**Pull request closed without merging**
