### PR TITLE
Fix the crash that occurs on the second attempt to instantiate the FMU

### PR DESCRIPTION
**Pull request by igor-epam**
if the first instance was destroyed. This crash is reproducible on recent Python versions. Although the documentation does not explicitly mention avoiding the use of PyFinalize more than once per process, doing so can lead to a crash in reality. To address this issue, keep the PyState alive until the library is unloaded.

### CODE REVIEW

**Comment by igor-epam** [comment]
@MinsGoing FYI

**Comment by igor-epam** [comment]
@markaren Please review the fix for the issue mentioned (for some reason) here https://github.com/igor-epam/co2_tracker/issues/8
There was a crash attempting to instantiate the second instance of FMU.

**Comment by MinsGoing** [comment]
@igor-epam It's working, thank you for your help. @markaren Please review the fix for the problem.

**Comment by Nils12345678901234567** [comment]
When I run an very simple FMU created with PythonFMU in MATLAB Simulink (R2024a) it always crashes on the second run. 

Could this be the same problem?

When will a new version of PythonFMU be released?

@zefir-o @markaren

**Comment by zefir-o** [comment]
@Nils12345678901234567 This fix is for the issue caused by the previous PR. It was never released though. If you are using the version from the pip, then it's a different issue.

**Comment by MinsGoing** [comment]
@Nils12345678901234567 You need to manually git clone repository and then install it

**Pull request merged**
