### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by eisDNV**

### CODE REVIEW

**Comment by markaren** [comment]
Could you provide some more information about this change? Are any of the files added autogenerated? In which case it would be better to leave them out and let the user run the necessary step to generate the documentation if needed (?). 

In any case, I think the README should be updated to reflect the changes and how to use it.

**Comment by eisDNV** [comment]
Hei,

the only changes in existing code concern updates of docstrings.
Beyond that I added the folder /doc and inside there /doc/source with the files required to configure Sphinx runs. The /doc/build directory is not included on github. That means that only everything needed to generate the documentation is included, but not the files generated by Sphinx runs.

Probably we should add the following at the end of the Readme.md:
'''The package includes documentation. Do the following to generate e.g. html documentation::
   cd /doc
   make html

The documentation is then available as `/doc/build/html/index.html`'''

Does that answer your questions?

Siegfried

**Comment by markaren** [comment]
I don't think the current state of this PR is mergable. It is not clear what sphinx does or how to use. The PR also adds duplication of files and files that need manual oversight in terms of potential code changes. 

The docstrings would be acceptable as is as a separate PR.

Closing for now.

**Comment by eisDNV** [comment]
Ok. This pull request is rather outdated. Our current internal version has superseded that and we will make a new pull request. With respect to sphinx, this is the recommended way to document python packages and we started to improve the documentation as part of our work to understand the package. Why does sphinx represent a problem? Is it only another dependency?

**Comment by markaren** [comment]
It's more that the PR does not explain itself weel enough. Further, `doc/source/modules.rst` seems to be an autogenerated file that sould not be included in the PR? If it is  ndeed intended, then it complicates the project as it needs manual maintance. The readme file is also duplicated.

**Pull request closed without merging**
