### PR TITLE
Release v0.4.0

### PR DESCRIPTION
**Pull request by fcollonval**
Should we release a new version?

### CODE REVIEW

**Comment by markaren** [comment]
I'd like to support reset first.

**Comment by markaren** [comment]
Uhm, wait until I've fixed the current regression

**Comment by markaren** [comment]
All good.

**Comment by markaren** [comment]
I'm seeing some issues on my end that needs to be resolved before a release.

**Comment by markaren** [comment]
See #51

**Comment by markaren** [comment]
We should push 0.4.0 today :)

**Comment by fcollonval** [comment]
Ok now I'm the one delaying it 😜 

Incoming PR to fix `FMPy` usage

**Pull request merged**
