### PR TITLE
Deployment cli

### LINKED ISSUE #87: Bundle a requirements.txt with the FMU
We should add an API function so the model implementer can specify which 3rd party libraries are required to run the model. This should result in a `requirements.txt` that the user manually copies or invoke a commandline option `pythonfmu -install-requirements path\to\fmu.fmu` that does this automatically.

### PR DESCRIPTION
**Pull request by fcollonval**
@markaren Here is a alternative to #89 to fix #87 

I updated the example notebook. And during that update, I got the confirmation that at least with `pyfmi`, using simultaneously two Python FMUs is not possible 😞

### CODE REVIEW

**Comment by markaren** [comment]
> using simultaneously two Python FMUs is not possible

Not at all or is it the loggers that don't work? If it's the former we need to fix that for sure as that was something that worked before introducing the logger.

**Comment by fcollonval** [comment]
> On a different note, I should probably refactor the csv stuff into a separate cli as you did with this one. `pythonfmu-csvbuilder`, which would allow for customization and separation of concern.

This is a great idea. One comment, should we move to a cli api like `pythonfmu _command_ options` rather than `pythonfmu-_command_ options` closer to package manager api?

**Comment by markaren** [comment]
> One comment, should we move to a cli api like pythonfmu _command_ options rather than pythonfmu-_command_ options closer to package manager api?

That might be reasonable

**Comment by fcollonval** [comment]
Ok so let's merge this and #98. And then we can do that in another PR.

**Pull request merged**
