### PR TITLE
Add log categories

### PR DESCRIPTION
**Pull request by fcollonval**

### CODE REVIEW

**Comment by markaren** [comment]
Better to define Enums? 
Also, is it possible to turn off adding trailing commas in your formatter?

**Comment by fcollonval** [comment]
> Better to define Enums?

I'ld like to keep the dictionary approach to allow user to modify the default list. For instance the standard specification mentioned the following list:

logEvents, logSingularLinearSystems, logNonlinearSystems, logDynamicStateSelection, logStatusWarning, logStatusDiscard, logStatusError, logStatusFatal, logStatusPending, logAll

_There are the standardized names for “Category” and these names should be used if a tool supports the corresponding log category._

So it could be interesting to let the user add/remove some categories depending on their model.

> Also, is it possible to turn off adding trailing commas in your formatter?

I'll do

**Comment by fcollonval** [comment]
@markaren I finally found the time to move forward on this. You will see in the test (`test_fmi2slave.py::test_Fmi2Slave_customized_log_categories`) an example to set different log categories.

**Comment by markaren** [comment]
> Remove unused return value

I realize this was not part of this PR, but but

**Pull request merged**
