### PR TITLE
Feature/no dll logging

### LINKED ISSUE #97: Using simultaneously two Python FMUs
> using simultaneously two Python FMUs seems not possible

Not at all or is it the loggers that don't work? If it's the former we need to fix that for sure as that was something that worked before introducing the logger.

_Originally posted by @markaren in https://github.com/NTNU-IHB/PythonFMU/pull/95#issuecomment-602067181_

Ok I started creating test case for co-simulation with multiple Python FMUs in https://github.com/NTNU-IHB/PythonFMU/tree/tdd-multiple-fmus.

The idea would be to use it to carry Test Driven Development on it.

Contrarily to what I said, you are right - at least with `pyfmi` - co-simulation of Python FMUs is possible. My problem was probably related to the test case. In the example notebook, I was trying to load a model with a missing dependency - using #95. And reloading the FMU after installing the dependency does not work as the import are ignored at the second call.

Could we keep this issue to track problem with co-simulation?

For now:

- [ ] When using `self.log` with co-simulation and `pyfmi` on both FMUs, the simulation is carried out. But at least on Windows, an error is thrown when the FMU models are deleted:
```
...\Temp\JModelica.org\jm_tmp3prdw82t\binaries\win64\Slave2.dll - Access refused.
```

### PR DESCRIPTION
**Pull request by markaren**
This PR avoids loading the logging dll from Python by polling log messages from the native side. This should avoid issues with loading the dll multiple times when multiple instances are loaded.

Should resolve #97

### CODE REVIEW

**Comment by markaren** [comment]
Still into this @fcollonval ?

**Comment by fcollonval** [comment]
@markaren thanks for pinging me.

Did you try to add a test case with 2 FMUs (see old commit for a basis: https://github.com/NTNU-IHB/PythonFMU/commit/82bf53070cab9fd878f250d509e3cc9e0b818b2b)?

I moved to a new company and I'm not using FMU there. May be a former colleague of mine would want to have a look @trungleduc.

**Comment by markaren** [comment]
Thanks, your old test works fine with this PR 👍

**Comment by fcollonval** [comment]
> Thanks, your old test works fine with this PR 👍

Awesome, great work!

**Review by fcollonval — APPROVED** [review]
LGTM

**Pull request merged**
